<?php

use Illuminate\Support\Facades\Schedule;

/*
|--------------------------------------------------------------------------
| Console Routes
|--------------------------------------------------------------------------
*/

/**
 * Delete expired Password reset tokens every 15 minutes
 */
Schedule::command('auth:clear-resets')->everyFifteenMinutes();

/**
 * Clean Laravel Debugbar cache daily
 */
Schedule::command('debugbar:clear')->daily();

/**
 * The optimize:clear method may be used to remove all the cache
 * files generated by the optimize command as well as all keys
 * in the default cache driver
 */
Schedule::command('optimize:clear')->daily();

/**
 * Clear Purify cache daily
 */
Schedule::command('purify:clear')->daily();
